export const PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const SINGLE_PRODUCTS_LOADING = "GET_SINGLE_PRODUCTS_LOADING";
export const SINGLE_PRODUCTS_SUCCESS = "GET_SINGLE_PRODUCTS_SUCCESS";
export const SINGLE_PRODUCTS_FAIL = "GET_SINGLE_PRODUCTS_FAIL";
