export const PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const SINGLE_PRODUCTS_LOADING = "GET_SINGLE_PRODUCTS_LOADING";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const LOAD_USER = "LOAD_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const REGISTER = "REGISTER";
export const RESET_PASSWORD = "RESET_PASSWORD";
