export const PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const LATEST_PRODUCT = "GET_LATEST_PRODUCT";
export const SEARCHED_PRODUCT = "GET_SEARCHED_PRODUCT";
export const SINGLE_PRODUCTS_LOADING = "GET_SINGLE_PRODUCTS_LOADING";

export const LOGIN = "LOGIN";
export const GOOGLE_SIGN_IN = "GOOGLE_SIGN_IN";
export const LOGOUT = "LOGOUT";
export const LOAD_USER = "LOAD_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const REGISTER = "REGISTER";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const ADD_LOCATION = "ADD_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";

export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const MULTIPLE_UPDATE_CART = "MULTIPLE_UPDATE_CART";
export const UPDATE_CART = "UPDATE_CART";
export const GET_CART = "GET_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const MULTIPLE_ADD_TO_CART = "MULTIPLE_ADD_TO_CART";

export const GET_ORDERS = "GET_ORDERS";
export const CREATE_ORDER = "CREATE_ORDER";
export const GET_SINGLE_ORDERS = "GET_SINGLE_ORDERS";
export const POST_REVIEW = "POST_REVIEW";

export const GET_COUPON = "GET_COUPON";
